name: "CI tests"

on:
  push:
    branches: [deadline_0]

jobs:

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Create CMake cache
        run: cmake -S . -B cmake-build-debug

      - name: Build target
        run: cmake --build cmake-build-debug --target itmoscript_tests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        working-directory: cmake-build-debug
        run: ctest --output-on-failure

